### ISSUE TITLE
Thanks for Starring my Project

### ISSUE THREAD

**Issue by Werner1201** [rafamerlin/pomodorino#11]
I'm here to thank you on starring my project. As a developer I'm thrilled that you liked my project, and I'm here to ask you to contribute there since I see that you have some appeal to linux, You could help us bring the Weather_Tray-rs to Linux too. We are still making improvements on the usability, requests and the navigation there, And We would love to have your contribution too. If Rust isn't know to you, give it a try, since making small programs is made simple in Rust but I digress. Thanks again for starring and Stay tuned on the project for updates and I hope you enjoy the App.

**Comment by rafamerlin** [comment]
Oh yeah, I'm trying to create a rust version this project (pomodorino) and I'm learning a lot. I'll make it public when it's usable, as right now it's just me using it as a playground to understand a bit more about rust. If I have any issues when trying pomodorino-rs in linux (currently working on windows dev env) It's likely I would have the same problems you'd on weather_tray-rs on linux so I may be able to help with some things in weather_tray-rs :)

Tenha um ótimo dia :)

**Comment by Werner1201** [comment]
Nossa vc também fala português? Não achei por causa de Melbourne Australia

Em qua, 26 de ago de 2020 20:17, Rafael Merlin <notifications@github.com>
escreveu:

**Comment by rafamerlin** [comment]
Opa, eu sou Brasileiro. Do interior de Sampa, mas moro em Melbourne.

Quando eu conseguir que o pomodorino-rs funcione do jeito que eu gostaria eu deixo ele público e te convido pro repositório. Uma coisa que estou fazendo ali é lidando com atualização do ícone (igual esse aplicativo faz) e também vou lidar com sons de alerta, acho que vou usar `rodio` pra chegar lá. Eu fiz um fork to `systray-rs` e adicionei algumas opções pra fazer minha vida ficar mais fácil, mas quando eu deixar o código disponível gostaria de um feedback pra ver se não estou fazendo besteira.

**Comment by Werner1201** [comment]
Tem um contribuidor no meu repo que ele tbm fez um fork tenta falar com ele
pra acrescentar suas modificações na versão dele. Pq nós já nos ajudamos
logo

Em qua, 26 de ago de 2020 20:26, Rafael Merlin <notifications@github.com>
escreveu:
